export type SupplyReceiptInit = {
    id?: number;
    receiptCode?: string | null;
    receiptNumber?: string | null;
    organizationName?: string | null;
    departmentName?: string | null;
    entryDate?: Date | string | null;
    debitAccount?: string | null;
    creditAccount?: string | null;
    delivererName?: string | null;
    sourceDocType?: string | null;
    sourceDocNo?: string | null;
    sourceDocDate?: Date | string | null;
    sourceDocIssuer?: string | null;
    warehouseId?: number | null;
    totalAmount?: number | null;
    attachedDocNote?: string | null;
    creatorName?: string | null;
    storekeeperName?: string | null;
    chiefAccountantName?: string | null;
    signedDate?: Date | string | null;
    createdAt?: Date | string | null;
    createdBy?: number | null;
    updatedAt?: Date | string | null;
    updatedBy?: number | null;
    isDeleted?: boolean;
    details?: SupplyReceiptDetailInit[];
};
import { SupplyReceiptDetail, type SupplyReceiptDetailInit } from './SupplyReceiptDetail.js';
export declare class SupplyReceipt {
    readonly id: number | undefined;
    readonly receiptCode: string | null;
    readonly receiptNumber: string | null;
    readonly organizationName: string | null;
    readonly departmentName: string | null;
    readonly entryDate: Date | null;
    readonly debitAccount: string | null;
    readonly creditAccount: string | null;
    readonly delivererName: string | null;
    readonly sourceDocType: string | null;
    readonly sourceDocNo: string | null;
    readonly sourceDocDate: Date | null;
    readonly sourceDocIssuer: string | null;
    readonly warehouseId: number | null;
    readonly attachedDocNote: string | null;
    readonly creatorName: string | null;
    readonly storekeeperName: string | null;
    readonly chiefAccountantName: string | null;
    readonly signedDate: Date | null;
    readonly createdAt: Date | null;
    readonly createdBy: number | null;
    readonly updatedAt: Date | null;
    readonly updatedBy: number | null;
    readonly isDeleted: boolean;
    readonly details: SupplyReceiptDetail[];
    readonly totalAmount: number;
    constructor(init?: SupplyReceiptInit);
    static fromRow(row: Record<string, unknown>, detailRows?: Record<string, unknown>[]): SupplyReceipt;
}
//# sourceMappingURL=SupplyReceipt.d.ts.map